title: Baihe Yan 's Homepage
page-top-title: Baihe Yan（闫柏赫）
top-section-bg-text: Computer Science
home-subtitle: Baihe Yan&ensp;|&ensp;闫柏赫
copyright-text: '&copy; Baihe Yan 2026. All Rights Reserved.'